/* eslint-disable no-restricted-globals */

// This service worker implements a comprehensive caching strategy for the PWA
// See https://developers.google.com/web/tools/workbox/modules

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell.
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }
    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    // If this looks like a URL for a resource, because it contains a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache images with CacheFirst strategy
// Images don't change often, so we can cache them aggressively
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.match(/\.(?:png|jpg|jpeg|svg|gif|webp)$/),
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache CSS and JavaScript files with StaleWhileRevalidate
// This strategy serves cached content immediately but updates in the background
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.match(/\.(?:js|css)$/),
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// Cache fonts with CacheFirst strategy
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.match(/\.(?:woff|woff2|ttf|otf|eot)$/),
  new CacheFirst({
    cacheName: 'fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// For API calls, use NetworkFirst with fallback to cache
// This ensures we get fresh data when online, but can work offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
      // In a real app, you would add BackgroundSyncPlugin here for offline data sync
      // new BackgroundSyncPlugin('api-queue', {
      //   maxRetentionTime: 24 * 60, // 24 hours
      // }),
    ],
  })
);

// Handle offline data sync for localStorage operations
// Since we're using localStorage, we don't need network sync,
// but we can add this for future backend integration
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-data') {
    event.waitUntil(
      // In a real app, sync with backend here
      Promise.resolve().then(() => {
        console.log('Data sync completed');
      })
    );
  }
});

// Handle push notifications (for future implementation)
self.addEventListener('push', (event) => {
  const data = event.data ? event.data.json() : {};
  const title = data.title || 'Bezetting App';
  const options = {
    body: data.body || 'Nieuwe notificatie',
    icon: '/logo192.png',
    badge: '/logo192.png',
    vibrate: [200, 100, 200],
    data: data,
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.openWindow(event.notification.data?.url || '/')
  );
});

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Clean up old caches on activation
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          // Delete old caches if needed
          // if (cacheName.startsWith('old-cache-')) {
          //   return caches.delete(cacheName);
          // }
        })
      );
    })
  );
});
